name: Deploy WebApp to Local Ubuntu Server

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Local Ubuntu Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 192.168.1.100
          username: prashik
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            rm -rf *
            git clone https://github.com/your-username/local-webapp-deployment.git .
            sudo systemctl restart nginx
